Repository TheXTech/TheXTech, pull requests merged in 2023-08, with the labels that each got.

#550 Enable keyhole fix permanently + gameplay timer initialisation fix
  changelog.txt
  src/compat.cpp
  src/compat.h
  src/config.h
  src/control/controls.cpp
  src/controls.h
  src/editor/editor.cpp
  src/editor/new_editor.cpp
  src/fontman/font_manager.cpp
  src/fontman/font_manager.h
  src/game_main.cpp
  src/graphics/gfx_enter_screen.cpp
  src/graphics/gfx_keyhole.cpp
  src/graphics/gfx_print.cpp
  src/graphics/gfx_update.cpp
  src/main/game_loop.cpp
  src/main/gameplay_timer.cpp
  src/main/main_config.cpp
  src/main/menu_controls.cpp
  src/main/menu_main.cpp
  src/main/outro_loop.cpp
  src/main/screen_connect.cpp
  src/main/screen_pause.cpp
  src/main/screen_prompt.cpp
  src/main/screen_quickreconnect.cpp
  src/main/screen_quickreconnect.h
  src/main/screen_textentry.cpp
  src/main/speedrunner.cpp
  src/main/world_loop.cpp
  src/player.cpp
  src/player/player_update.cpp
Labels: enhancement, speedrun

#583 Quick backport of scale mode feature from multires
  changelog.txt
  resources/languages/thextech_en.json
  resources/languages/thextech_zh-cn.json
  src/change_res.cpp
  src/change_res.h
  src/core/16m/window_16m.cpp
  src/core/3ds/render_3ds.cpp
  src/core/3ds/window_3ds.cpp
  src/core/base/events_base.cpp
  src/core/base/render_base.h
  src/core/base/window_base.h
  src/core/minport/render_minport_shared.cpp
  src/core/null/window_null.cpp
  src/core/sdl/render_sdl.cpp
  src/core/sdl/render_sdl.h
  src/core/sdl/window_sdl.cpp
  src/core/sdl/window_sdl.h
  src/core/wii/window_wii.cpp
  src/core/window.h
  src/main/main_config.cpp
  src/main/menu_main.cpp
  src/main/menu_main.h
  src/main/translate.cpp
  src/video.h
Labels: visuals

#595 Simple pre-processor for message boxes
  CMakeLists.txt
  changelog.txt
  src/layers.cpp
  src/player/player_update.cpp
  src/script/msg_preprocessor.cpp
  src/script/msg_preprocessor.h
Labels: enhancement
